name: shelfservice-nestjs
version: 0.0.0
description: Backend for Workflow-Manager ShelfService
author: Marvin Peter
private: true
license: UNLICENSED
scripts:
  prebuild: rimraf dist
  build: nest build
  start: nest start
  start:dev: nest start --watch
  start:debug: nest start --debug --watch
  start:prod: node dist/main
  prepare: if test "$CI" != 1; then husky install ; fi
  prettier: >-
    prettier --write
    "{src,cypress}/**/*.{js,json,css,scss,less,md,ts,html,component.html}"
  prettier:check: >-
    prettier --check
    "{src,cypress}/**/*.{js,json,css,scss,less,md,ts,html,component.html}"
  lint: eslint "{src,apps,libs,test}/**/*.ts" --fix
  test:debug: |-
    node --inspect-brk
      -r tsconfig-paths/register
      -r ts-node/register node_modules/.bin/jest
      --runInBand
  test:unit: jest --config ./jest.config.ts
  test:unit-ci: $npm_execpath run test:unit --ci --runInBand --forceExit --coverage
  test:e2e: jest --config ./test/jest-e2e.config.ts
  test:e2e-ci: $npm_execpath run test:e2e --ci --runInBand --forceExit --coverage
  test:all: $npm_execpath run test:unit && $npm_execpath run test:e2e
  test:all-ci: >-
    $npm_execpath run test:unit-ci && $npm_execpath run test:e2e-ci &&
    $npm_execpath run test:merge-coverage
  test:merge-coverage: >-
    istanbul-merge --out ./coverage-all/coverage.json
    ./coverage/coverage-final.json ./coverage-e2e/coverage-final.json &&
    istanbul report --root ./coverage-all --dir ./coverage-all/html html
  devenv:setup: docker-compose -f dev/docker-compose.yml --profile dev up -d
  devenv:setup-ci: docker-compose -f dev/docker-compose.yml --profile ci up -d
  devenv:teardown: docker-compose -f dev/docker-compose.yml down
  typeorm: >-
    while read line; do export $line; done < .env > /dev/null &&
    typeorm-ts-node-commonjs --dataSource
    ./src/config/typeorm-config/typeorm-config.service.ts
dependencies:
  '@kubernetes/client-node': ^0.17.0
  '@nestjs/common': 9.0.1
  '@nestjs/config': 2.2.0
  '@nestjs/core': 9.0.1
  '@nestjs/mapped-types': '*'
  '@nestjs/microservices': ^9.1.4
  '@nestjs/platform-express': 9.0.1
  '@nestjs/schedule': ^2.1.0
  '@nestjs/swagger': 6.0.1
  '@nestjs/typeorm': 9.0.0
  class-transformer: 0.5.1
  class-validator: 0.13.2
  keycloak-connect: 18.0.2
  nest-keycloak-connect: 1.9.0
  pg: 8.7.3
  reflect-metadata: 0.1.13
  rimraf: 3.0.2
  rxjs: 7.5.5
  typeorm: 0.3.7
  uuid: ^8.3.2
  webpack: 5.73.0
devDependencies:
  '@commitlint/cli': 17.0.3
  '@commitlint/config-conventional': 17.0.3
  '@nestjs/cli': 9.0.0
  '@nestjs/schematics': 9.0.1
  '@nestjs/testing': 9.0.1
  '@semantic-release/commit-analyzer': 9.0.2
  '@types/eventsource': ^1.1.9
  '@types/express': 4.17.13
  '@types/jest': 28.1.4
  '@types/node': 18.0.3
  '@types/supertest': 2.0.12
  '@types/uuid': ^8.3.4
  '@typescript-eslint/eslint-plugin': 5.30.5
  '@typescript-eslint/parser': 5.30.5
  commitlint: 17.0.3
  conventional-changelog-conventionalcommits: 5.0.0
  eslint: 8.19.0
  eslint-config-prettier: 8.5.0
  eslint-plugin-import: ^2.26.0
  eslint-plugin-prettier: 4.2.1
  eventsource: ^2.0.2
  husky: 8.0.1
  istanbul: ^0.4.5
  istanbul-merge: ^1.1.1
  jest: 28.1.2
  lint-staged: 13.0.3
  prettier: 2.7.1
  semantic-release: 19.0.3
  source-map-support: 0.5.21
  supertest: 6.2.4
  ts-jest: 28.0.5
  ts-loader: 9.3.1
  ts-node: 10.8.2
  tsconfig-paths: 4.0.0
  tslint-config-prettier: 1.18.0
  typescript: 4.7.4
